### PR TITLE
Anything you need to read death numer from the memory

### PR DESCRIPTION
**Pull request by igromanru**
- git module added: ProcessMemory
- added DeathAddress with current pointer into Logic-Class
- changed Application build to 64bit, it's needed for the memory stuff.
- Admin rights needed

### CODE REVIEW

**Comment by igromanru** [comment]
I hope you know how git modules work.

**Comment by davidgcs** [comment]
Hi igromanru thanks for taking your time to look at the code, I dont really know at all of the git functions because I just started to use it, it seem that you added a submodule and I can see the code by github (I merged it) but when I try to download it I see nothing inside the ProcessMemory directory.
Im going to try by updating it through visual studio and lets see what happens. Is it necessary to do something to make it works? or just starting the game and the application will it work? I could not check all the code yet but I will get to it. Anyway thanks for your help and for your time 👍

**Comment by davidgcs** [comment]
PD: im going to add you on the contributors in the mod's page, do you want something in special for me to add? any website for example?

**Comment by igromanru** [comment]
- I don't know what you are using as git interface, but I recommend you [TortoiseGit](https://tortoisegit.org/), because not matter which IDE or language you are using, you can always use TortoiseGit.
- To get content of a git submodule, you have to initialize/update it first. Read [this](https://github.com/blog/2104-working-with-submodules). If you are planning to use TortoiseGit then [here](https://tortoisegit.org/docs/tortoisegit/tgit-dug-submodules.html)
- It's okey if you just just give me credits in your application. :) You can also link http://ds3.igromanru.guide/, but if you don't want to spread cheats, I'm ok with it.  

EDIT: Wtf, why have you reverted changes?
649150445ebeda372a11d9db17382822ca8287e6

**Comment by davidgcs** [comment]
I don't know because visual studio is very confusing with git so I tried to access to the submodule and it seem I revert changes, how can I merge it again, do you have to commit changes again or its not necessary? Im going to try this TortoiseGit maybe I can find the option there

I have add you on the mods page and a link to your page and when we fix the merge problem and everything is done im going to set a prompt when closing the app to thank you there too 👍

**Pull request merged**
